### PR TITLE
new changes to branch "Hero"

### PR DESCRIPTION
**Pull request by WojciechDutkiewicz**
I've finished my work with Hero Section (mobile version)

### CODE REVIEW

**Review by KJachimstal — CHANGES_REQUESTED** [review]
Everything is OK. Just before mege pull recent changes from main and resolve conflicts. Nice work!

**Comment by rsciupider** [comment]
Looks fine to me

**Review by matilis — APPROVED** [review]
Logo IceCream is in Header.

**Review by KJachimstal — CHANGES_REQUESTED** [review]
Missing desktop and tablet features.

**Review by rsciupider — APPROVED** [review]

**Pull request closed without merging**
